### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by userkilled**
The story of the runoff, which was not in Tusk, was the most successful. They were translated and added

### CODE REVIEW

**Comment by kyori19** [comment]
@userkilled it looks like your change contains duplicate string entry

**Comment by userkilled** [comment]
Yesh, i fix it

**Comment by userkilled** [comment]
I probably don’t understand much, but is it worth highlighting the translation of yuito into a separate file so as not to conflict with each update of the file. or it doesn’t work like that?? (translate)

**Comment by kyori19** [comment]
@userkilled That's a nice idea! I didn't thought of it. I will consider taking that approach.
Anyway, thanks for your contribution! CI failure is not your fault, and I will merge this PR.

**Pull request merged**
